version: '3'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always

  web:
    image: nginx:alpine
    container_name: example-webapp
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=app1.marrara.net
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=app1.marrara.net
      - LETSENCRYPT_EMAIL=rafael@marrara.net
    restart: always


  app:
    build: app
    container_name: app
    depends_on:
      - redis
    expose:
      - "5000"
    volumes:
      - ./app:/code
    environment:
      - FLASK_ENV=development
      - VIRTUAL_HOST=app2.marrara.net
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=app2.marrara.net
      - LETSENCRYPT_EMAIL=rafael@marrara.net
    restart: always

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always



volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  default:
    external:
      name: nginx-proxy
